name: Man10MythicMagic
version: '1.0'
main: tororo1066.man10mythicmagic.Man10MythicMagic
api-version: '1.19'
loader: tororo1066.man10mythicmagic.DependencyLoader

dependencies:
  server:
    MythicMobs:
      load: BEFORE
      required: false
    Magic:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    NMSUtils:
      load: BEFORE
    ProtocolLib:
      load: BEFORE
      required: false