name: Man10MythicMagic
version: '${version}'
main: tororo1066.man10mythicmagic.Man10MythicMagic
api-version: 1.19

commands:
  mythicmagic:
softdepend:
  - AmmoPlugin
  - ArmorEquipEvent
  - Magic
  - MythicMobs
  - WorldGuard
depend:
  - NMSUtils