name: CI

on:
  push:
    branches: [ master ]
    tags:
    - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
   
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Man10MythicMagic-1.0-SNAPSHOT.jar
        path: build/libs/Man10MythicMagic-1.0-SNAPSHOT.jar

    
